### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2105-t13-3j/main#2]
Suggestions on a nice project name!

**Comment by TimothyTam** [comment]
EzScheduler
LazyScheduler
WongKinFei
ScheduleBuddy

**Comment by WongKinFei** [comment]
WorkCompanion

**Comment by TimothyTam** [comment]
ScheduleBuddy
exBuddy

**Comment by C-YanHua** [comment]
I guess we have decided on "Task Commando" as our project name.
